/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const MsDarkMode: typeof import('~icons/material-symbols/dark-mode.svelte')['default']
  const MsFlight: typeof import('~icons/material-symbols/flight.svelte')['default']
  const MsInfoOutline: typeof import('~icons/material-symbols/info-outline.svelte')['default']
  const MsLightMode: typeof import('~icons/material-symbols/light-mode.svelte')['default']
}
